### ISSUE TITLE
Failed to compile Ubuntu 16.04

### ISSUE THREAD

**Issue by edulopez44** [OpenKitten/MongoKitten#53]
/Packages/MongoKitten-1.7.1/Sources/MongoKitten/GridFS.swift:161:41: error: cannot convert value of type 'Int64' to expected dictionary value type 'Value'
                                   "n": ~Int64(n),
                                        ^~~~~~~~~
                                        Value(   )

MongoKitten fails to compile on ubuntu 16.04

**Comment by Joannis** [comment]
We're not supporting 1.7.1 anymore. I'll see when I can release a patch for this. If you want to have this issue resolved quickly I'd recommend updating to the mostly-compatible MK 2.0 release.

**Comment by Joannis** [comment]
As a clarification @edulopez44. We do not support 1.7.1, so we can't promise you an update. But I think it's important/relevant enough to fix this soon.

**Comment by Joannis** [comment]
What xcode version are you running @edulopez44 ? I think you're running a beta version of Xcode with an older beta version of Swift 3.0.

**Comment by JustinM1** [comment]
See #55 for solution

**Comment by Joannis** [comment]
@edulopez44 is this fix working for you?

**Comment by edulopez44** [comment]
It is working with the latest version. Thank you!
